import { useState } from 'react';

const ButtonsAlerts = () => {
    const [confirmResult, setConfirmResult] = useState('');
    const [promptResult, setPromptResult] = useState('');

    const triggerAlert = () => {
        window.alert('This is a native browser alert!');
    };

    const triggerConfirm = () => {
        const result = window.confirm('Do you accept the terms and conditions?');
        if (result) {
            setConfirmResult('You selected: OK');
        } else {
            setConfirmResult('You selected: Cancel');
        }
    };

    const triggerPrompt = () => {
        const result = window.prompt('Please enter your automation framework name:');
        if (result !== null) {
            setPromptResult(`You entered: ${result}`);
        } else {
            setPromptResult('Prompt was cancelled.');
        }
    };

    return (
        <div>
            <div className="mb-8">
                <h2 className="text-2xl font-bold text-gray-800">Native Buttons & Alerts</h2>
                <p className="text-gray-600 mt-2">
                    Write scripts to handle synchronous blocking dialogs generated by the browser.
                    Use your framework to accept/dismiss the dialogues and assert on the results below.
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Native Alert Card */}
                <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 text-center hover:border-blue-300 transition-colors">
                    <div className="h-12 w-12 bg-amber-100 text-amber-600 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                    </div>
                    <h3 className="text-lg font-bold mb-2 text-gray-900">Native Alert</h3>
                    <p className="text-gray-500 text-sm h-10 mb-6">Triggers an OK dialog that completely blocks browser execution.</p>
                    <button
                        id="alertBtn"
                        onClick={triggerAlert}
                        className="w-full bg-slate-800 hover:bg-slate-900 text-white font-medium py-2.5 rounded-lg transition-colors shadow-sm"
                    >
                        Trigger Alert
                    </button>
                    <div className="mt-4 h-10 flex items-center justify-center">
                        <span className="text-xs text-gray-400 italic">No return value</span>
                    </div>
                </div>

                {/* Native Confirm Card */}
                <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 text-center hover:border-emerald-300 transition-colors">
                    <div className="h-12 w-12 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"></path></svg>
                    </div>
                    <h3 className="text-lg font-bold mb-2 text-gray-900">Native Confirm</h3>
                    <p className="text-gray-500 text-sm h-10 mb-6">Requires the script logic to make a choice between OK and Cancel.</p>
                    <button
                        id="confirmBtn"
                        onClick={triggerConfirm}
                        className="w-full bg-slate-800 hover:bg-slate-900 text-white font-medium py-2.5 rounded-lg transition-colors shadow-sm"
                    >
                        Trigger Confirm
                    </button>
                    <div className="mt-4 h-10 flex items-center justify-center w-full">
                        {confirmResult ? (
                            <div id="confirmResult" className="w-full py-2 bg-gray-50 text-emerald-700 text-sm font-semibold rounded border border-emerald-100">
                                {confirmResult}
                            </div>
                        ) : (
                            <span className="text-xs text-gray-400">Waiting for trigger...</span>
                        )}
                    </div>
                </div>

                {/* Native Prompt Card */}
                <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 text-center hover:border-purple-300 transition-colors">
                    <div className="h-12 w-12 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center mx-auto mb-4">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg>
                    </div>
                    <h3 className="text-lg font-bold mb-2 text-gray-900">Native Prompt</h3>
                    <p className="text-gray-500 text-sm h-10 mb-6">Prompts the script to type text directly into the native browser dialog.</p>
                    <button
                        id="promptBtn"
                        onClick={triggerPrompt}
                        className="w-full bg-slate-800 hover:bg-slate-900 text-white font-medium py-2.5 rounded-lg transition-colors shadow-sm"
                    >
                        Trigger Prompt
                    </button>
                    <div className="mt-4 h-10 flex items-center justify-center w-full">
                        {promptResult ? (
                            <div id="promptResult" className="w-full py-2 bg-gray-50 text-purple-700 text-sm font-semibold rounded border border-purple-100">
                                {promptResult}
                            </div>
                        ) : (
                            <span className="text-xs text-gray-400">Waiting for string...</span>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ButtonsAlerts;
